# Generated by Django 4.1.4 on 2022-12-14 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_nordigen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nordigen_id', models.CharField(max_length=100, unique=True)),
                ('api_data', models.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nordigen_id', models.UUIDField(unique=True)),
                ('reference_id', models.UUIDField()),
                ('completed', models.BooleanField(default=False)),
                ('api_data', models.JSONField(blank=True, null=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_nordigen.institution')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_nordigen.integration')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
