# Generated by Django 4.1.4 on 2022-12-15 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_nordigen', '0002_institution_requisition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nordigen_id', models.UUIDField()),
                ('api_data', models.JSONField()),
                ('api_details', models.JSONField()),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_nordigen.institution')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_nordigen.integration')),
                ('requisitions', models.ManyToManyField(blank=True, to='django_nordigen.requisition')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
