# Generated by Django 4.1.4 on 2022-12-15 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_nordigen', '0005_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='max_historical_days',
            field=models.PositiveSmallIntegerField(default=90),
            preserve_default=False,
        ),
    ]
