# Generated by Django 4.1.4 on 2022-12-15 12:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_nordigen", "0007_alter_transaction_nordigen_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="balance",
            name="type",
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
