# Generated by Django 4.1.4 on 2022-12-15 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_nordigen', '0008_balance_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-booking_date', '-pk']},
        ),
    ]
