# Generated by Django 4.1.4 on 2022-12-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_nordigen", "0009_alter_transaction_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="synced_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterModelOptions(
            name="account",
            options={"ordering": ["-synced_at"]},
        ),
        migrations.AddField(
            model_name="balance",
            name="synced_at",
            field=models.DateTimeField(null=True),
        ),
    ]
