# Generated by Django 4.1.4 on 2023-02-07 17:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_nordigen", "0010_account_synced_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="nordigen_id",
            field=models.UUIDField(unique=True),
        ),
        migrations.AlterField(
            model_name="integration",
            name="nordigen_id",
            field=models.UUIDField(unique=True),
        ),
    ]
