# Generated by Django 4.1.4 on 2023-03-13 09:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_nordigen", "0011_alter_account_nordigen_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="alias",
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
