# Generated by Django 4.1.4 on 2023-03-14 10:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_nordigen", "0012_account_alias"),
    ]

    operations = [
        migrations.AddField(
            model_name="requisition",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
